const PROFILE={height:2.10,length:5.304,width:1.904,mirrors:2.297};
const COLORS={green:'#24b35a',yellow:'#e9c914',orange:'#ef8d19',red:'#df443b',grey:'#89939d'};
const map=L.map('map',{zoomControl:true}).setView([54.4,-3.1],6);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const roadsLayer=L.layerGroup().addTo(map),restrictionLayer=L.layerGroup().addTo(map);
let roads=[],roadEntries=[],filter='all';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function roadPopup(p){return `<b>${esc(p.name)}</b><br><span class="rating" style="color:${COLORS[p.rating]}">${esc(p.rating)}</span><br>${esc(p.reason)}<br><br><a href="${esc(p.source)}" target="_blank" rel="noopener">Evidence / map reference</a>`}
fetch('./roads.geojson').then(r=>{if(!r.ok)throw Error(`roads ${r.status}`);return r.json()}).then(data=>{roads=data.features||[];roads.forEach(f=>{const p=f.properties;const layer=L.geoJSON(f,{style:{color:COLORS[p.rating]||COLORS.grey,weight:p.rating==='green'?5:7,opacity:.9}}).bindPopup(roadPopup(p));layer.addTo(roadsLayer);roadEntries.push({feature:f,layer})});renderRoadSearch()}).catch(err=>{console.error(err);document.getElementById('roadResults').textContent='Road dataset could not be loaded.'});
function renderRoadSearch(){const q=document.getElementById('roadSearch').value.trim().toLowerCase(),box=document.getElementById('roadResults');roadEntries.forEach(x=>x.layer.setStyle({opacity:(filter==='all'||x.feature.properties.rating===filter)?.9:.1}));if(!q){box.innerHTML=`Search <b>${roads.length}</b> researched/classified corridors.`;return}const hits=roadEntries.filter(x=>(filter==='all'||x.feature.properties.rating===filter)&&`${x.feature.properties.name} ${x.feature.properties.region}`.toLowerCase().includes(q)).slice(0,10);box.innerHTML=hits.length?'':'No researched match yet.';hits.forEach(x=>{const p=x.feature.properties,d=document.createElement('div');d.className='result';d.innerHTML=`<b>${esc(p.name)}</b> <span class="badge" style="background:${COLORS[p.rating]}">${esc(p.rating)}</span><br>${esc(p.region)}`;d.onclick=()=>{map.fitBounds(x.layer.getBounds(),{padding:[40,40]});x.layer.openPopup();closeMobile()};box.appendChild(d)})}
document.getElementById('roadSearch').addEventListener('input',renderRoadSearch);document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.rating;renderRoadSearch()});
async function placeSearch(e){e.preventDefault();const q=document.getElementById('placeSearch').value.trim(),box=document.getElementById('placeResults');if(!q)return;box.textContent='Searching…';try{const u='https://nominatim.openstreetmap.org/search?format=json&countrycodes=gb&limit=6&q='+encodeURIComponent(q);const rs=await fetch(u,{headers:{Accept:'application/json'}}).then(r=>r.json());box.innerHTML=rs.length?'':'No UK match found.';rs.forEach(r=>{const d=document.createElement('div');d.className='result';d.textContent=r.display_name;d.onclick=()=>{if(r.boundingbox)map.fitBounds([[+r.boundingbox[0],+r.boundingbox[2]],[+r.boundingbox[1],+r.boundingbox[3]]]);else map.setView([+r.lat,+r.lon],14);closeMobile()};box.appendChild(d)})}catch{box.textContent='Place search is temporarily unavailable.'}}
document.getElementById('placeForm').addEventListener('submit',placeSearch);
function num(v){const m=String(v||'').match(/\d+(?:\.\d+)?/);return m?+m[0]:null}
function restrictionText(t){const bits=[];[['maxheight','height',PROFILE.height],['maxwidth','width',PROFILE.mirrors],['maxlength','length',PROFILE.length]].forEach(([k,label,ours])=>{if(t[k]){const n=num(t[k]);bits.push(`${label}: ${esc(t[k])}${n&&n<ours?' — TOO SMALL FOR PENFOLD':''}`)}});if(t.maxweight)bits.push(`weight: ${esc(t.maxweight)}`);if(t.barrier)bits.push(`barrier: ${esc(t.barrier)}`);if(t.ford!==undefined||t.highway==='ford')bits.push('ford');return bits.join('<br>')||'Mapped vehicle restriction'}
async function checkRestrictions(){const b=map.getBounds(),status=document.getElementById('restrictionStatus');restrictionLayer.clearLayers();status.textContent='Checking OpenStreetMap restrictions…';const s=b.getSouth(),w=b.getWest(),n=b.getNorth(),e=b.getEast();if((n-s)*(e-w)>8){status.textContent='Zoom in a little first — the visible area is too large for a useful restriction check.';return}const q=`[out:json][timeout:25];(way["maxheight"](${s},${w},${n},${e});way["maxwidth"](${s},${w},${n},${e});way["maxlength"](${s},${w},${n},${e});way["maxweight"](${s},${w},${n},${e});node["barrier"~"height_restrictor|bollard|gate"](${s},${w},${n},${e});node["ford"](${s},${w},${n},${e});way["ford"](${s},${w},${n},${e}););out center tags;`;try{const data=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q,headers:{'Content-Type':'text/plain'}}).then(r=>{if(!r.ok)throw Error();return r.json()});data.elements.forEach(el=>{const lat=el.lat??el.center?.lat,lon=el.lon??el.center?.lon;if(lat==null)return;const t=el.tags||{},danger=(num(t.maxheight)&&num(t.maxheight)<PROFILE.height)||(num(t.maxwidth)&&num(t.maxwidth)<PROFILE.mirrors)||(num(t.maxlength)&&num(t.maxlength)<PROFILE.length);const marker=L.marker([lat,lon],{icon:L.divIcon({className:'restriction-icon',html:danger?'!':'R',iconSize:[26,26]})}).bindPopup(`<b>${danger?'Potential Penfold conflict':'Mapped restriction'}</b><br>${restrictionText(t)}`);marker.addTo(restrictionLayer)});status.textContent=`Found ${data.elements.length} mapped restriction${data.elements.length===1?'':'s'} in this view.`}catch{status.textContent='Restriction service did not respond. Try again shortly.'}}
document.getElementById('restrictionBtn').onclick=checkRestrictions;
const panel=document.getElementById('panel');document.getElementById('panelToggle').onclick=()=>panel.classList.toggle('open');function closeMobile(){if(innerWidth<=720)panel.classList.remove('open')}
L.control.layers(null,{'Penfold researched roads':roadsLayer,'Mapped restrictions':restrictionLayer},{collapsed:true}).addTo(map);