const PROFILE={height:2.10,length:5.304,width:1.904,mirrors:2.297};
const COLORS={green:'#24b35a',yellow:'#e9c914',orange:'#ef8d19',red:'#df443b',grey:'#89939d'};
const map=L.map('map',{zoomControl:true}).setView([54.4,-3.1],6);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const roadsLayer=L.layerGroup().addTo(map),restrictionLayer=L.layerGroup().addTo(map);
let roads=[],roadEntries=[],filter='all';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function roadPopup(p){const evidence=p.evidence?`<br><br><small><b>Evidence:</b> ${esc(p.evidence)}${p.confidence?` · <b>Confidence:</b> ${esc(p.confidence)}`:''}</small>`:'';return `<b>${esc(p.name)}</b><br><span class="rating" style="color:${COLORS[p.rating]}">${esc(p.rating)}</span><br>${esc(p.reason)}${evidence}<br><br><a href="${esc(p.source)}" target="_blank" rel="noopener">Evidence / map reference</a>`}
Promise.all(['./roads.geojson','./roads-expansion-1.geojson','./roads-expansion-2.geojson'].map(u=>fetch(u).then(r=>{if(!r.ok)throw Error(`${u} ${r.status}`);return r.json()}))).then(datasets=>{roads=datasets.flatMap(d=>d.features||[]);roads.forEach(f=>{const p=f.properties;const layer=L.geoJSON(f,{style:{color:COLORS[p.rating]||COLORS.grey,weight:p.rating==='green'?5:7,opacity:.9}}).bindPopup(roadPopup(p));layer.addTo(roadsLayer);roadEntries.push({feature:f,layer})});renderRoadSearch()}).catch(err=>{console.error(err);document.getElementById('roadResults').textContent='Road dataset could not be loaded.'});
function renderRoadSearch(){const q=document.getElementById('roadSearch').value.trim().toLowerCase(),box=document.getElementById('roadResults');roadEntries.forEach(x=>x.layer.setStyle({opacity:(filter==='all'||x.feature.properties.rating===filter)?.9:.1}));if(!q){box.innerHTML=`Search <b>${roads.length}</b> researched/classified corridors.`;return}const hits=roadEntries.filter(x=>(filter==='all'||x.feature.properties.rating===filter)&&`${x.feature.properties.name} ${x.feature.properties.region}`.toLowerCase().includes(q)).slice(0,10);box.innerHTML=hits.length?'':'No researched match yet.';hits.forEach(x=>{const p=x.feature.properties,d=document.createElement('div');d.className='result';d.innerHTML=`<b>${esc(p.name)}</b> <span class="badge" style="background:${COLORS[p.rating]}">${esc(p.rating)}</span><br>${esc(p.region)}`;d.onclick=()=>{map.fitBounds(x.layer.getBounds(),{padding:[40,40]});x.layer.openPopup();closeMobile()};box.appendChild(d)})}
document.getElementById('roadSearch').addEventListener('input',renderRoadSearch);document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.rating;renderRoadSearch()});
async function placeSearch(e){e.preventDefault();const q=document.getElementById('placeSearch').value.trim(),box=document.getElementById('placeResults');if(!q)return;box.textContent='Searching…';try{const u='https://nominatim.openstreetmap.org/search?format=json&countrycodes=gb&limit=6&q='+encodeURIComponent(q);const rs=await fetch(u,{headers:{Accept:'application/json'}}).then(r=>r.json());box.innerHTML=rs.length?'':'No UK match found.';rs.forEach(r=>{const d=document.createElement('div');d.className='result';d.textContent=r.display_name;d.onclick=()=>{if(r.boundingbox)map.fitBounds([[+r.boundingbox[0],+r.boundingbox[2]],[+r.boundingbox[1],+r.boundingbox[3]]]);else map.setView([+r.lat,+r.lon],14);closeMobile()};box.appendChild(d)})}catch{box.textContent='Place search is temporarily unavailable.'}}
document.getElementById('placeForm').addEventListener('submit',placeSearch);
function num(v){const m=String(v||'').match(/\d+(?:\.\d+)?/);return m?+m[0]:null}
function restrictionKind(t){if(t.maxheight)return 'height';if(t.maxwidth)return 'width';if(t.maxlength)return 'length';if(t.maxweight)return 'weight';if(t.barrier==='height_restrictor')return 'height';if(t.ford!==undefined||t.highway==='ford')return 'ford';return 'other'}
function restrictionDanger(t){return (num(t.maxheight)&&num(t.maxheight)<=2.20)||(num(t.maxwidth)&&num(t.maxwidth)<=2.05)||(num(t.maxlength)&&num(t.maxlength)<=PROFILE.length)}
function restrictionSymbol(t){const kind=restrictionKind(t);if(kind==='height')return `H${t.maxheight?` ${esc(t.maxheight)}`:''}`;if(kind==='width')return `W${t.maxwidth?` ${esc(t.maxwidth)}`:''}`;if(kind==='length')return 'L';if(kind==='weight')return 't';if(kind==='ford')return 'FORD';return 'R'}
function restrictionText(t){const bits=[];if(t.maxheight){const n=num(t.maxheight);bits.push(`<b>Height:</b> ${esc(t.maxheight)}${n&&n<=2.20?' — PENFOLD WARNING':''}`)}if(t.maxwidth){const n=num(t.maxwidth);bits.push(`<b>Width:</b> ${esc(t.maxwidth)}${n&&n<=2.05?' — VERY TIGHT FOR PENFOLD':''}`)}if(t.maxlength){const n=num(t.maxlength);bits.push(`<b>Length:</b> ${esc(t.maxlength)}${n&&n<=PROFILE.length?' — TOO SHORT FOR PENFOLD':''}`)}if(t.maxweight)bits.push(`<b>Weight:</b> ${esc(t.maxweight)}`);if(t.barrier==='height_restrictor')bits.push('<b>Physical height restrictor</b>');if(t.ford!==undefined||t.highway==='ford')bits.push('<b>Ford</b> — assess depth and flow locally');return bits.join('<br>')||'Mapped vehicle restriction'}
const OVERPASS_ENDPOINTS=[{name:'Main OSM',url:'https://overpass-api.de/api/interpreter'},{name:'Private.coffee',url:'https://overpass.private.coffee/api/interpreter'},{name:'VK Maps',url:'https://maps.mail.ru/osm/tools/overpass/api/interpreter'}];
async function fetchOverpass(query,status){let lastErr=null;for(let i=0;i<OVERPASS_ENDPOINTS.length;i++){const ep=OVERPASS_ENDPOINTS[i];status.textContent=`Checking restrictions… ${i?`trying backup ${i+1}/${OVERPASS_ENDPOINTS.length}`:'using main service'}`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const body='data='+encodeURIComponent(query);const res=await fetch(ep.url,{method:'POST',body,signal:controller.signal,headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','Accept':'application/json'}});clearTimeout(timer);if(!res.ok)throw Error(`${ep.name} HTTP ${res.status}`);const data=await res.json();return {data,server:ep.name}}catch(err){clearTimeout(timer);lastErr=err;console.warn(`Overpass failed: ${ep.name}`,err)}}throw lastErr||Error('All Overpass services failed')}
async function checkRestrictions(){const b=map.getBounds(),status=document.getElementById('restrictionStatus');restrictionLayer.clearLayers();const s=b.getSouth(),w=b.getWest(),n=b.getNorth(),e=b.getEast();if((n-s)*(e-w)>3){status.textContent='Zoom in a little first — a smaller area makes the restriction check much more reliable.';return}const q=`[out:json][timeout:12];(nwr["maxheight"](${s},${w},${n},${e});nwr["maxwidth"](${s},${w},${n},${e});nwr["maxlength"](${s},${w},${n},${e});nwr["maxweight"](${s},${w},${n},${e});node["barrier"="height_restrictor"](${s},${w},${n},${e});nwr["ford"](${s},${w},${n},${e}););out center tags qt;`;try{const {data,server}=await fetchOverpass(q,status);data.elements.forEach(el=>{const lat=el.lat??el.center?.lat,lon=el.lon??el.center?.lon;if(lat==null)return;const t=el.tags||{},kind=restrictionKind(t),danger=restrictionDanger(t),symbol=restrictionSymbol(t);const marker=L.marker([lat,lon],{icon:L.divIcon({className:`restriction-icon restriction-${kind}${danger?' restriction-danger':''}`,html:symbol,iconSize:null})}).bindPopup(`<b>${danger?'Potential Penfold conflict':kind==='ford'?'Ford':'Mapped vehicle restriction'}</b><br>${restrictionText(t)}`);marker.addTo(restrictionLayer)});status.textContent=`Found ${data.elements.length} vehicle-relevant restriction${data.elements.length===1?'':'s'} in this view via ${server}.`}catch(err){console.error(err);status.textContent='All restriction services were busy or unavailable. Zoom in further and try again.'}}
document.getElementById('restrictionBtn').onclick=checkRestrictions;
const panel=document.getElementById('panel');document.getElementById('panelToggle').onclick=()=>panel.classList.toggle('open');function closeMobile(){if(innerWidth<=720)panel.classList.remove('open')}
L.control.layers(null,{'Penfold researched roads':roadsLayer,'Mapped vehicle restrictions':restrictionLayer},{collapsed:true}).addTo(map);